apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-code-configmap
  namespace: llm
data:
  metrics_exporter.py: |
    from flask import Flask, Response, request
    import requests
    import threading

    app = Flask(__name__)

    OLLAMA_URL = "http://localhost:11434"
    inflight_requests = 0
    lock = threading.Lock()

    @app.route('/proxy', methods=['POST'])
    def proxy():
        global inflight_requests
        with lock:
            inflight_requests += 1
        try:
            resp = requests.post(f"{OLLAMA_URL}/api/generate", json=request.get_json())
            return Response(resp.content, status=resp.status_code, content_type=resp.headers.get('Content-Type'))
        finally:
            with lock:
                inflight_requests -= 1

    @app.route('/metrics')
    def metrics():
        return Response(f"dummy_inflight_requests {inflight_requests}\n", mimetype="text/plain")

    if __name__ == "__main__":
        app.run(host="0.0.0.0", port=9090, threaded=True)




