apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: llm
  labels:
    app: ollama
spec:
  selector:
    app: ollama
  ports:
    - name: http
      port: 9090
      targetPort: 9090
