apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter
  namespace: monitoring
data:
  config.yaml: |
    rules:
      - seriesQuery: 'dummy_inflight_requests{namespace!=""}'
        resources:
          overrides:
            namespace:
              resource: "namespace"
            pod:
              resource: "pod"
        name:
          matches: "dummy_inflight_requests"
          as: "dummy_inflight_requests"
        metricsQuery: 'avg(dummy_inflight_requests{<<.LabelMatchers>>}) by (namespace, pod)'