apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter
  namespace: monitoring
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prometheus-adapter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/part-of: prometheus-adapter
    app.kubernetes.io/version: v0.12.0
data:
  config.yaml: |
    rules:
    - seriesQuery: 'ollama_proxy_active_requests{namespace!="",deployment!=""}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          deployment:
            resource: "deployment"
      name:
        matches: '^ollama_proxy_active_requests$'
        as: 'ollama_proxy_active_requests'
      metricsQuery: 'sum(ollama_proxy_active_requests{namespace="llm"}) by (namespace, deployment)'
