apiVersion: v1
data:
  config.yaml: |
    rules:
      - seriesQuery: 'dummy_inflight_requests{namespace!=""}'
        resources:
          overrides:
            namespace:
              resource: "namespace"
            pod:
              resource: "pod"
        name:
          matches: "dummy_inflight_requests"
          as: "dummy_inflight_requests"
        metricsQuery: 'avg(dummy_inflight_requests{<<.LabelMatchers>>}) by (namespace, pod)'
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"rules:\n  - seriesQuery: 'dummy_inflight_requests{namespace!=\"\"}'\n    resources:\n      overrides:\n        namespace:\n          resource: \"namespace\"\n        pod:\n          resource: \"pod\"\n    name:\n      matches: \"dummy_inflight_requests\"\n      as: \"dummy_inflight_requests\"\n    metricsQuery: 'avg(dummy_inflight_requests{\u003c\u003c.LabelMatchers\u003e\u003e}) by (namespace, pod)'\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"prometheus-adapter","namespace":"monitoring"}}
    meta.helm.sh/release-name: prometheus-adapter
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-08-04T05:37:38Z"
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prometheus-adapter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-adapter
    app.kubernetes.io/part-of: prometheus-adapter
    app.kubernetes.io/version: v0.12.0
    helm.sh/chart: prometheus-adapter-4.14.2
  name: prometheus-adapter
  namespace: monitoring
  resourceVersion: "22003"
  uid: dea37252-4de1-4fb8-9276-5cd348f3e8c0
