apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_MODELS
          value: /root/.ollama
        volumeMounts:
        - name: ollama-storage
          mountPath: /root/.ollama
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                # Run ollama pull in background so container startup isn't blocked.
                (ollama list > /root/.ollama/pull.log 2>&1 || true) &
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
            # aliyun.com/gpu-mem: "2"
            nvidia.com/gpu: "1"
          limits:
            cpu: "1000m"
            memory: "2Gi"
            # aliyun.com/gpu-mem: "2"
            nvidia.com/gpu: "1"
      volumes:
      - name: ollama-storage
        persistentVolumeClaim:
          claimName: ollama-pvc