apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_MODELS
          value: "llama3.2:3b"
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                # Run ollama pull in background so container startup isn't blocked.
                (ollama pull llama3.2:3b > /root/.ollama/pull.log 2>&1 || true) &
        resources:
          requests:
            cpu: "250m"  # 0.25 CPU
            memory: "512Mi"
            aliyun.com/gpu-mem: "2"  # Request 2GiB GPU memory
          limits:
            cpu: "1000m" # 1 CPU
            memory: "2Gi"
            aliyun.com/gpu-mem: "2"  # Limit to 2GiB GPU memory
      volumes:
      - name: ollama-data
        emptyDir: {}