apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-proxy
  namespace: ollama
  labels:
    app: ollama-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-proxy
  template:
    metadata:
      labels:
        app: ollama-proxy
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/path: "/metrics"
      #   prometheus.io/port: "9090"
    spec:
      containers:
      - name: ollama-proxy
        image: python:3.11-slim
        command:
          - /bin/sh
          - -c
          - |
            pip install aiohttp && \
            python /app/proxy_server.py
        workingDir: /app
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: proxy-code
          mountPath: /app
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: proxy-code
        configMap:
          name: ollama-proxy-code
