apiVersion: v1
kind: Service
metadata:
  name: ollama-proxy
  namespace: ollama
  labels:
    app: ollama-proxy
    release: kube-prometheus-stack-1754283167
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ollama-proxy
