apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter
  namespace: ollama
  labels:
    app: prometheus-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-adapter
  template:
    metadata:
      labels:
        app: prometheus-adapter
    spec:
      serviceAccountName: prometheus-adapter
      containers:
        - name: adapter
          image: registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.12.0
          args:
            - --config=/etc/adapter/config.yaml
            - --logtostderr=true
            - --metrics-relist-interval=1m
            - --prometheus-url=http://kube-prometheus-stack-1754-prometheus.prometheus.svc:9090

              # ^ adjust to your Prometheus service DNS name/port
          volumeMounts:
            - name: config
              mountPath: /etc/adapter
          ports:
            - name: https
              containerPort: 6443
      volumes:
        - name: config
          configMap:
            name: custom-metrics-config
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-adapter
  namespace: ollama
spec:
  selector:
    app: prometheus-adapter
  ports:
    - name: https
      port: 443
      targetPort: 6443
