apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-nfs-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.140.81.161
    path: /mnt/data/ollama